"""update name

Revision ID: aee32d9e34c9
Revises: c27c385d7e34
Create Date: 2025-10-13 22:39:32.520941

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aee32d9e34c9'
down_revision: Union[str, Sequence[str], None] = 'c27c385d7e34'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('zones', sa.Column('place', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('zones', 'place')
    # ### end Alembic commands ###
