"""next update

Revision ID: c27c385d7e34
Revises: a8836c7c280d
Create Date: 2025-10-11 17:53:14.260303

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c27c385d7e34'
down_revision: Union[str, Sequence[str], None] = 'a8836c7c280d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('official_outages', 'zone')
    op.add_column('reports', sa.Column('latitude', sa.Float(), nullable=True))
    op.add_column('reports', sa.Column('longitude', sa.Float(), nullable=True))
    op.add_column('reports', sa.Column('zone_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'reports', 'zones', ['zone_id'], ['id'])
    op.drop_column('reports', 'zone')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reports', sa.Column('zone', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'reports', type_='foreignkey')
    op.drop_column('reports', 'zone_id')
    op.drop_column('reports', 'longitude')
    op.drop_column('reports', 'latitude')
    op.add_column('official_outages', sa.Column('zone', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
